controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.3
    wheels_radius: 0.05

    pose_reference_frame: odom

    odom_frame_id: odom
    base_frame_id: base_footprint

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    publish_limited_velocity: true
    use_stamped_vel: false

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        has_acceleration_limits: true
        max_acceleration: 0.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 1.0

joint_broad:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster